### ISSUE TITLE
Updating timer interval

### ISSUE THREAD

**Issue by petitssoldats** [khoih-prog/NRF52_MBED_TimerInterrupt#1]
Hi! Is it possible to update/change timer interval?
Thanks :)

**Comment by khoih-prog** [comment]
Certainly it's possible to change it on-the-fly.

I've just added new example [**Change_Interval**](https://github.com/khoih-prog/NRF52_MBED_TimerInterrupt/tree/main/examples/Change_Interval) to demonstrate how to update/change Timer Interval whenever you'd like.
