### ISSUE TITLE
analogRead 

### ISSUE THREAD

**Issue by Hamajo** [khoih-prog/NRF52_MBED_TimerInterrupt#2]
I tried using the Argument_None Example that you have on Ardiuno Nano 33 Sense and it worked perfectly fine.
The issue is whenever I add a analogRead within any of the Interrupt Service Routines the program will freeze after the first printResult function. To even upload a new sketch the Ardiuno Nano 33 Sense has to be but into bootloader mode.

**Comment by khoih-prog** [comment]
There are many commands you can't use inside ISR.

For Nano-33-BLE / Sense, **analogRead/analogWrite are commands not to be used in ISRs.**

You can just set a flag, then call analogRead inside a timer's loop.
