### ISSUE TITLE
NRF52_MBED_Timer's  TimerHandler delay

### ISSUE THREAD

**Issue by klyatskin** [khoih-prog/NRF52_MBED_TimerInterrupt#4]
```
// Arduino Nano 33 BLE

#define TIMER_INTERRUPT_DEBUG         0
#define _TIMERINTERRUPT_LOGLEVEL_     0
#define HW_TIMER_INTERVAL_MS      1

#include "NRF52_MBED_TimerInterrupt.h"
#include "NRF52_MBED_ISR_Timer.h"

NRF52_MBED_Timer ITimer(NRF_TIMER_3);

// Init NRF52 timer NRF_TIMER3
NRF52_MBED_Timer ITimer(NRF_TIMER_3);
// Init NRF52_MBED_ISRTimer
// Each NRF52_MBED_ISRTimer can service 16 different ISR-based timers
NRF52_MBED_ISRTimer ISR_Timer;

#define TIMER_INTERVAL_1s    1000L

volatile static unsigned int count = 0;
void TimerHandler() {
    count += 1;
    if (count % 100000 == 0) // **** should happen every 1 sec? - does not work
        digitalWrite(LED_PWR, !digitalRead(LED_PWR)); 
    ISR_Timer.run();
}


void onTimer1s() { // once per 1 sec. - it works
     digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN));
   }


void setup() {
    // Interval in microsecs
    if (ITimer.attachInterruptInterval(HW_TIMER_INTERVAL_MS * 1000/100, TimerHandler)) {  // **** every 10 us?
        // Serial.print(F("Starting ITimer OK, millis() = ")); Serial.println(millis());
    } else {
       //  Serial.println(F("Can't set ITimer. Select another freq. or timer"));
    }
    ISR_Timer.setInterval(TIMER_INTERVAL_1s, onTimer1s); 
 }


void loop() {
}
```

For some reason LED_PWR blink are about twice as slow... onTimer1s works as expected.

**Comment by klyatskin** [comment]
Good morning,

This sample code for test blinking works but the higher frequency it has
the lower accuracy is reached for the blink period.
I used 10us just to illustrate that while the code works the blinking
period is about doubled from expected.

What I need is 150us frequency for 50% load pwm. Can I do it accurately
through the interrupt?
Is there any better way to chat with you?

Thank you anyway for the library. It works well for me with other projects.
-- 
Konstantin

**Comment by khoih-prog** [comment]
Glad to know that it's somehow helpful to you and you're very welcome.

> What I need is 150us frequency for 50% load pwm.

You have to write the code yourself or use any PWM library working with MBED Nano-33-BLE. If there is no ready-made library, just port any PWM one to NRF52 MBED platform.

It all depends on your code (using how **many MCU cycles**, etc. ) and the core. 
Also don't use **time-consuming** `ISR_Timer.setInterval()` which is designed for slow-pacing jobs.

> Is there any better way to chat with you?

Sorry, I won't do this. You're on your own
