### ISSUE TITLE
Procedure For Installing MBED 1.3.2

### ISSUE THREAD

**Issue by GaryDT** [khoih-prog/NRF52_MBED_TimerInterrupt#8]
I'm using a Nano 33 BLE, and the Arduino IDE.

I know that Timer 1 doesn't work for the latest MBED versions, which I discovered myself before reading other peoples reports.

Therefore, I have two questions...

1) Please describe the procedure for installing MBED 1.3.2 (and will this then mean that timer 1 will work after doing this?)

2) Does this library make use of all 16 bit timers, e.g., will 10 micro seconds (or even lower, perhaps 1) be accurate? like when setting registers directly, as demonstrated in various AVR examples.

Thank you, Gary.

Edit 1: ah! so for micro second precision we need the following maybe...

#include <hal/nrf_timer.h>
#include <hal/nrf_gpiote.h>
#include <hal/nrf_gpio.h>
#include <hal/nrf_ppi.h>

Please kindly confirm if this library uses the above for the Nano 33 BLE?

Edit 2: my sincere apologies for editing again, but I'm trying to understand the fundamentals...

[NRF52840 Timers... "5×32 bit 16MHz Timer"](https://jimmywongiot.com/2019/10/07/how-to-use-the-rtc-timer-as-the-stop-watch-at-nordic-nrf5-sdk/)

So for the Nano 33 BLE... is this correct? so potentially extremely accurate via using the GPIOTE.

Edit 3: the timers are listed in the 1st table on this page as well [Nordic's NRF52 Timer Info](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fstruct_nrf52%2Fstruct%2Fnrf52.html)

**Comment by khoih-prog** [comment]
Hi @GaryDT 

Thanks for your interests in the library and it's good you spent some time to research before posting issue.

> 1. Please describe the procedure for installing MBED 1.3.2 (and will this then mean that timer 1 will work after doing this?)

1. This is actually a basic question for Arduino forum, but anyway, just go to `Tools` => `Board Manager`, then select according to the following picture

![Selection_071](https://user-images.githubusercontent.com/57012152/141000155-09d9a6eb-5b70-423c-ae46-b0dffd58b520.png)

You actually can install both v1.3.2 and v2.5.2+, at the same time, to use and test

> 2. Does this library make use of all 16 bit timers, e.g., will 10 micro seconds (or even lower, perhaps 1) be accurate? like when setting registers directly, as demonstrated in various AVR examples.

2. Check [NRF52_MBED_TimerInterrupt.h#L108-L115](https://github.com/khoih-prog/NRF52_MBED_TimerInterrupt/blob/main/src/NRF52_MBED_TimerInterrupt.h#L108-L115) 

```
const char* NRF52_MBED_TimerName[NRF_MAX_TIMER] =
{
  "NRF_TIMER0",
  "NRF_TIMER1",
  "NRF_TIMER2-DON'T_USE_THIS",
  "NRF_TIMER3",
  "NRF_TIMER4",
};
```

To use Timer Interrupt correctly, you must have certain hardware /firmware knowledge, read MCU documents, core and/or library, and examples' codes and fully understand to the bit / register / timings level.

The library is just a simple wrapper for you to simplify / speed-up the job. You have to **investigate and test yourself to see if it can help with your special or demanding use cases.**

I'm so sorry I don't have time now to help you.

Good Luck,

**Comment by GaryDT** [comment]
That's all a really great help actually (Y) it really is, so thank you kindly :) Please close again.
